USE [master]
GO

/****** Object:  Database [db_IDZ_Kozlov_v5]    Script Date: 25.12.2018 12:34:04 ******/
CREATE DATABASE [db_IDZ_Kozlov_v5]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\data.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ),
FILEGROUP FIRST_GROUP
 (NAME = N'FG1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FG1.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB),
 FILEGROUP SECOND_GROUP
 (NAME = N'FG2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FG2.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB)
 LOG ON 
( NAME = N'db_IDZ_Kozlov_v5_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\db_IDZ_Kozlov_v5_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )

GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_IDZ_Kozlov_v5].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET  MULTI_USER 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET QUERY_STORE = OFF
GO

ALTER DATABASE [db_IDZ_Kozlov_v5] SET  READ_WRITE 
GO


